force-app/main/default/objects/Audit_Log_Entry__c/Audit_Log_Entry__c.object-meta.xml
<CustomObject>
    <description>Referenced to an auditing log from Github&apos;s orgs.</description>
    <label>Audit Log Entry</label>
    <nameField>
        <label>Audit Log Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>The action of the user.</description>
    <label>Action</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>The country of where the user performed the action.</description>
    <label>Country Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Github_User__c.field-meta.xml
<CustomField>
    <fullName>Github_User__c</fullName>
    <description>The github username of the employee</description>
    <label>Github-User</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>The timestamp of when this action was done or created.</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/githubAPI.cls
public with sharing class githubAPI {
    public static String BASE_URL = 'https://api.github.com/';

        //Method to perform a callout and return an httpResponse
    public static httpResponse callout(String httpMethod, String endpoint){
        //Instantiate an httpRequest and set the required attributes
        httpRequest req = new httpRequest();
        req.setMethod(httpMethod);
        req.setEndpoint('callout:GithubAPI' + endpoint);
    
            //Optional attributes are often required to conform to the 3rd Party Web Service Requirements
        req.setHeader('Accept-Encoding','gzip, deflate');
    
            //You can adjust the timeout duration (in milliseconds) to deal with slow servers or large payloads
        req.setTimeout(120000);
    
            //Use the HTTP Class to send the httpRequest and receive an httpResposne
            /*If you are not using an HttpCalloutMock: 
            if (!test.isRunningTest){
            */
        httpResponse res = new http().send(req);
            /*If you are not using an HttpCalloutMock: 
            }
            */
            // system.debug(res.toString());
        return res;
    }

public void main(){
    callout('GET', '/orgs/auditing-tool-tester/auditlog');
    //sfdx force:data:tree:export -q "SELECT Github_User__c, Timestamp__c, Country_Code__c, Action__c FROM Audit_Log_Entry__c" -d ./data

}

}