force-app/main/default/objects/Audit_Log_Entry__c/Audit_Log_Entry__c.object-meta.xml
<CustomObject>
    <description>Referenced to an auditing log from Github&apos;s orgs.</description>
    <label>Audit Log Entry</label>
    <nameField>
        <label>Audit Log Entry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Audit Log Entries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Access_Recipient__c.field-meta.xml
<CustomField>
    <fullName>Access_Recipient__c</fullName>
    <description>The Github username that is receiving access or permissions.</description>
    <label>Access Recipient</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Action__c.field-meta.xml
<CustomField>
    <fullName>Action__c</fullName>
    <description>The action of the user.</description>
    <label>Action</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <description>The name of the branch that the user is working on.</description>
    <label>Branch Name</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Country_Code__c.field-meta.xml
<CustomField>
    <fullName>Country_Code__c</fullName>
    <description>The country of where the user performed the action.</description>
    <label>Country Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Document_ID__c.field-meta.xml
<CustomField>
    <fullName>Document_ID__c</fullName>
    <description>The Github document ID that is associated with this action.</description>
    <label>Document_ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Github_User__c.field-meta.xml
<CustomField>
    <fullName>Github_User__c</fullName>
    <description>The github username of the employee</description>
    <label>Github-User</label>
    <length>45</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Org__c.field-meta.xml
<CustomField>
    <fullName>Org__c</fullName>
    <description>The name of the org that the user is in.</description>
    <label>Org</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Repository__c.field-meta.xml
<CustomField>
    <fullName>Repository__c</fullName>
    <description>The name of the repository that the user is working on.</description>
    <label>Repository</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Audit_Log_Entry__c/fields/Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timestamp__c</fullName>
    <description>The timestamp of when this action was done or created.</description>
    <label>Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/AuditLogEntrySearchController.cls
public with sharing class AuditLogEntrySearchController {
    @AuraEnabled
    public static List<Audit_Log_Entry__c> searchLogs( String searchTerm ) {
        List<Audit_Log_Entry__c> audit_log_entries = new List<Audit_Log_Entry__c>();
        if ( String.isNotBlank( searchTerm ) ) {
            List<List<SObject>> searchResults = [
                FIND :searchTerm
                RETURNING Audit_Log_Entry__c(
                    Timestamp__c, Github_User__c, Action__c, Repository__c, Branch_Name__c, Access_Recipient__c, Country_Code__c, Org__c, Document_ID__c
                    ORDER BY Timestamp__c
                    LIMIT 100
                )
            ];
            audit_log_entries = searchResults[0];
        }
        else{
            List<List<SObject>> searchResults = [
                FIND : 'auditing-tool-tester'
                RETURNING Audit_Log_Entry__c(
                    Timestamp__c, Github_User__c, Action__c, Repository__c, Branch_Name__c, Access_Recipient__c, Country_Code__c, Org__c, Document_ID__c
                    ORDER BY Timestamp__c
                    LIMIT 250
                )
            ];
        }
        return audit_log_entries;
    }
}